# Generated by Django 4.0.5 on 2022-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_editprofile_createprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprofile',
            name='skill',
            field=models.CharField(default='tehran', max_length=100),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
