# Generated by Django 4.0.5 on 2022-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_createprofile_skill_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='createprofile',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='profile_picture'),
        ),
    ]
