# Generated by Django 4.0.5 on 2022-06-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_createprofile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createprofile',
            name='img',
        ),
    ]
