# Generated by Django 4.0.5 on 2022-06-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Change',
        ),
    ]
