# Generated by Django 4.0.5 on 2022-06-30 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_profile_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='image',
            field=models.ImageField(default='profile_picture/default.jpg', upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='change',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
