# Generated by Django 4.0.5 on 2022-06-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_change_image_alter_change_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Change',
        ),
    ]
